name: Frontend CI checks
on: 
    push:
        branches: 
            - main
    pull_request:
        types:
            - opened
        branches:
            - main

jobs:
    check-formatting-and-code:
        runs-on: ubuntu-latest
    
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: install nix
              uses: DeterminateSystems/nix-installer-action@main
            - run: nix run .#actions-frontend-script
    